minipoc_analytics:
  outputs:
    dev:
      dbname: pgsql_db
      host: postgres
      pass: app_pwd
      port: 5432
      schema: staging
      threads: 1
      type: postgres
      user: app_user
  target: dev
sales_dbt:
  outputs:
    dev:
      dbname: pgsql_db
      host: postgres
      pass: app_pwd
      port: 5432
      schema: dtmart_lyr
      threads: 1
      type: postgres
      user: app_user

    demo:
      type: postgres
      host: postgres
      user: app_user
      pass: app_pwd
      dbname: pgsql_db
      port: 5432
      schema: dtmart_demo     # schema untuk demo dbt run
      thread: 1
  target: dev                 # default tetap ke dev
